source_root      = 'original'
destination_root = 'translation'
output_root      = '.'

[[profiles]]
format = 'glossary'
source      = '%source_root%\evergreen_l_english.yml'
destination = '%destination_root%\evergreen_l_english.yml'
output      = '%output_root%\glossary'
